GET http://localhost:3111/api/blogs

###

POST http://localhost:3111/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZ1bnVzZXJuYW1lIiwiaWQiOiI2Njg1ZDI5MzE4MjQwMDc3ZDc4ZTM3YjMiLCJpYXQiOjE3MjAwNDYyMzR9.aLddOSYiobNgFw9IvMj8rG1Lp2k5B1ENvIpJ575JsXY

{
   "title": "Posting is fun, with mongoose!",
  "author": "OJ Simpson",
  "url": "www.mongodb.com",
  "likes": 348
}

###

GET http://localhost:3111/api/users HTTP/1.1

###

DELETE http://localhost:3111/api/users HTTP/1.1


###

POST http://localhost:3111/api/users HTTP/1.1
Content-Type: application/json

{
   "username": "funusername",
   "password": "funpassword"
}

###

POST http://localhost:3111/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "funusername",
  "password": "funpassword"
}

###

POST http://localhost:3111/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZ1bnVzZXJuYW1lIiwiaWQiOiI2Njg1ZDI5MzE4MjQwMDc3ZDc4ZTM3YjMiLCJpYXQiOjE3MjAwNDYyMzR9.aLddOSYiobNgFw9IvMj8rG1Lp2k5B1ENvIpJ575JsXY

{
  "title": "Tiddle taddle picked a ball", 
  "author": "Happy Lotter",
  "url": "www.thisissite.com"
}

###

DELETE http://localhost:3111/api/blogs/6685d3ce7090529bb7dffb24 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZ1bnVzZXJuYW1lIiwiaWQiOiI2Njg1ZDI5MzE4MjQwMDc3ZDc4ZTM3YjMiLCJpYXQiOjE3MjAwNDYyMzR9.aLddOSYiobNgFw9IvMj8rG1Lp2k5B1ENvIpJ575JsXY