GET http://localhost:3000/api/blogs

###

POST http://localhost:3000/api/blogs HTTP/1.1
Content-Type: application/json

{
   "title": "Posting is fun, with mongoose!",
  "author": "OJ Simpson",
  "url": "www.mongodb.com",
  "likes": 348
}

###

GET http://localhost:3111/api/users HTTP/1.1

###

DELETE http://localhost:3111/api/users HTTP/1.1


###

POST http://localhost:3111/api/users HTTP/1.1
Content-Type: application/json

{
   "username": "funusername",
   "password": "funpassword"
}

###

POST http://localhost:3111/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "funusername",
  "password": "funpassword"
}